env="dev"
product_name = "mirailifecare"
region = "us-east-2"
vpc_id="vpc-034f9a31ef8d68503"
db_name="mirailifecaredb"
db_user_name= "mirailifecaredbuser"
db_password = "!YourPwd#Should$BeLong%And^Secure"
db_instance_size="db.t2.large"
db_instance_disk_size = 50